### ISSUE TITLE
Multiple Next Hop Addresses - failover operation fails 

### ISSUE THREAD

**Issue by vvt137** [F5Networks/f5-cloud-failover-extension#44] opened 2020-08-11 07:03 UTC
## Description

I am trying to use the declaration from the following CFE CloudDocs article:

https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/example-declarations.html#multiple-next-hop-addresses

The declaration is successfully loaded, but when failover is triggered, the following error message is generated:

Tue, 11 Aug 2020 06:15:56 GMT - severe: [f5-cloud-failover] Cannot read property 'NetworkInterfaceId' of undefined TypeError: Cannot read property 'NetworkInterfaceId' of undefined at _listNics.then.nics (/var/config/rest/iapps/f5-cloud-failover/nodejs/providers/aws/cloud.js:485:51)

I also tested a similar declaration using "discoveryType":"routeTag" and obtained exactly the same error message.

If I remove the "192.168.12.0/24" clause, corresponding to the internal selfIPs, from the declaration failover is successful.

I am using an AWS CloudFormation template based on the following F5-supported template:

https://github.com/F5Networks/f5-aws-cloudformation/tree/master/supported/failover/across-net/via-api/3nic/existing-stack/payg

## Declaration code

My declaration code is below (the only differences with the example are the "debug" log level; "mydeployment" tags replaced with "slb1ha"; selfIPs are replaced with my external and internal selfIP pairs: 10.120.2.200,10.120.3.86 and 10.120.4.152, 10.120.5.12 respectively).

    {
        "class": "Cloud_Failover",
          "controls":{
          "class":"Controls",
          "logLevel":"debug"
        },
        "environment": "aws",
        "externalStorage": {
          "scopingTags": {
            "f5_cloud_failover_label": "slb1ha"
          }
        },
        "failoverAddresses": {
          "enabled": true,
          "scopingTags": {
            "f5_cloud_failover_label": "slb1ha"
          }
        },
        "failoverRoutes": {
          "enabled": true,
          "scopingTags": {
            "f5_cloud_failover_label": "slb1ha"
          },
          "scopingAddressRanges": [
            {
              "range": "192.168.11.0\/24",
              "nextHopAddresses": {
                "discoveryType": "static",
                "items": [
                  "10.120.2.200",
                  "10.120.3.86"
                ]
              }
            },
            {
              "range": "192.168.12.0\/24",
              "nextHopAddresses": {
                "discoveryType": "static",
                "items": [
                  "10.120.4.152",
                  "10.120.5.12"
                ]
              }
            }
          ]
        }
    }

**Comment by vvt137** [comment] 2020-08-12 02:51
The issue was caused by the F5-supported AWS CFT quoted above. The template tags only BIG-IPs' external AWS ENIs with "f5_cloud_failover_label" (using Stack Name as a value). The BIG-IPs' internal ENIs remain untagged and referring to the corresponding selfIPs from the declaration causes the failover to fail.

CFE documentation in Cloud-docs https://clouddocs.f5.com/products/extensions/f5-cloud-failover/latest/userguide/aws.html#aws does contain the corresponding statement:

> > You must tag the following resources. Even if you only have routes to update during failover (for example, there are no Elastic IPs to re-map) you still have to tag the NICs on the Virtual Machines associated with the IPs in your CFE declaration.

It may be worth adding to the document that both external and internal ENIs/NICs need to be tagged for the design shown on the diagram to work.

I have raised a separate issue ticket in the f5-aws-cloudformation repo: https://github.com/F5Networks/f5-aws-cloudformation/issues/124

**Comment by f5-chidambaram** [comment] 2020-08-18 07:21
Thanks for reporting this. We are tracking this item in our backlog, AUTOSDK-426. May I know the version of CFE that this occurred?

**Comment by vvt137** [comment] 2020-08-19 02:29
I worked with the current (master) version of the AWS CFT template - 5.7.0, which uses CFE v1.4.0

**Comment by f5-chidambaram** [comment] 2020-08-19 18:41
Thanks. The root cause of the issue is being tracked with Cloud Templates internal ID ESECLDTPLT-2181. I am closing this item here. Thank you!

**Closed by f5-chidambaram** 2020-08-19 18:41 UTC
